### PR TITLE
Feature/basic-chat-app-with-flagging

### PR DESCRIPTION
**Pull request by burtenshaw**
This PR includes a basic chatting app that stores feedback in a dataframe.

Next step: push dataframe to dataset repo

### CODE REVIEW

**Comment by davidberenstein1957** [comment]
@burtenshaw https://huggingface.co/docs/huggingface_hub/main/en/guides/upload#scheduled-uploads

**Comment by burtenshaw** [comment]
> @burtenshaw https://huggingface.co/docs/huggingface_hub/main/en/guides/upload#scheduled-uploads

Nice. Are you suggesting that I use it for the upload step?

**Comment by davidberenstein1957** [comment]
@burtenshaw It might help for inspiration. I am not sure how I implemented the flagging myself, but I believe it logs continuously (every interaction) instead of periodically as the implementation above but I guess it could work either way.

**Comment by burtenshaw** [comment]
> @burtenshaw It might help for inspiration. I am not sure how I implemented the flagging myself, but I believe it logs continuously (every interaction) instead of periodically as the implementation above but I guess it could work either way.

I'll add it to give us options. But we're still early so need to decide.

**Comment by burtenshaw** [comment]
@davidberenstein1957 I've added persistence, so now I think we should move on to inference. The only outstanding issue are unique identifiers for user and session, this will make it easier for us to deal with the data downstream.

**Comment by davidberenstein1957** [comment]
@burtenshaw I will have a look later today.

**Pull request merged**
